import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import Modals from "./Modals";

const font = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-gray-300 ${font.className}`}>
        <Modals />
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
